version: '3.7'
services:
  server:
    build:
      context: .
    container_name: IIA_server
    environment:
      DATABASE_HOST: postgres
    networks:
      IIA-network:
        aliases:
          - server
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - .:/app
      - ~/.cache/yarn:/app/node_modules

  postgres:
    image: postgres:15.1
    container_name: IIA_postgres
    volumes:
      - ./scripts/SQL/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    networks:
      - IIA-network
    logging:
      options:
        max-size: 10m
        max-file: '3'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: IIA_redis
    command: redis-server --appendonly yes
    restart: always
    networks:
      - IIA-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 15s
      retries: 1

    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.2'
          memory: 256M

networks:
  IIA-network:
    name: IIA-network

volumes:
  pg_data: {}
  redis_data: {}
  node_modules: {}
