#!/bin/bash
echo "===================================="
echo "Git Pre-Commit Hook"
echo "===================================="

# Running lint-staged
if npx lint-staged; then
  exit 0
else
  exit 1
fi
